const { MessageEmbed, Client, Intents } = require('discord.js');

const intents = [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MEMBERS];

// Client creation
const discordClient = new Client({ 
    presence: { status: "invisible" },
    intents: intents
});


const embeds = {

        /**
     * Warning Embed: Used to issue warnings to users.
     */
        warning: function() {
            return new MessageEmbed()
                .setColor("#ff0000")
                .setTitle("User Warning")
                .setDescription(`User: ${user}\n\nReason: ${reason}\n\n`)
                .setTimestamp()
                .setAuthor(discordClient.user.username, discordClient.client.user.displayAvatarURL());
        },
    referral: new MessageEmbed()
        .setColor('#4CAF50')
        .setTitle('🌟 Referral Information 🌟')
        .setDescription("When purchasing a VerusID, **Verus Coin Foundation@** can be used as a referral.\n\n**Paddypool@** can also be used.\n\n🚀 All fees generated by **Paddypool@** referrals will be shared among all of you who are actively mining. 🚀\n\nThank you for your support!"
        ),
    welcome: new MessageEmbed()
        .setColor('#0099ff')
        .setTitle('Welcome to PaddyPool! 🍀')
        .setDescription(
            `Welcome to the server,!\n\n` +
            '🌟 Dive into the ultimate pool of opportunities with PaddyPool! 🏊‍♂️\n\n' +
            '🚀 Explore our vibrant community of enthusiasts, and learners in the realm of mining, bridges, baskets & much more.\n\n' +
            '🔍 Whether you\'re seeking advice, sharing your expertise, or simply looking to connect, you\'ve landed in the right place!\n\n' +
            '💡 Check out our channels to engage in discussions, share resources, and stay updated on the latest trends and developments.\n\n' +
            '🔗 Don\'t forget to review our guidelines in the rules channel before diving in. Let\'s make this community thrive together!'
        ),
    reminder: new MessageEmbed()
        .setColor('#00FF00')
        .setTitle('Reminder:')
        .setDescription(
            `Remember\n\n` +
            'Turn on bot notifications to get notified when the pool finds blocks.\n\n' +
            'It will also allow you to compare with a list of known miners for the tipbot.\n\n' +
            'Users can get and load up their tipbot address, and tip helpful members.\n\n' +
            'This tipbot can only be used here on Paddypool, so make sure if you withdraw, you own the address you\'re sending to.\n\n' +
            'You can help support the pool by spreading the word on your social media accounts.\n\n' +
            'Thanks for joining Paddypool 🍀 🫂'
        ),
    rules: new MessageEmbed()
        .setColor('#ff0000')
        .setTitle('PaddyPool Server Rules:')
        .setDescription(
            `Hello User\n\n` +
            'Before you start exploring, make sure to read and understand our server rules:\n\n' +
            '1. **Respect Each Other:** Treat fellow members with kindness and respect. Discrimination, harassment, or any form of disrespectful behavior will not be tolerated.\n\n' +
            '2. **Keep It Civil:** Engage in constructive discussions and debates. Disagreements are natural, but personal attacks or inflammatory remarks are not acceptable.\n\n' +
            '3. **Stay on Topic:** Keep conversations relevant to the channel\'s theme. Off-topic discussions can be taken to appropriate channels or direct messages.\n\n' +
            '4. **No Spamming or Self-Promotion:** Avoid excessive posting of repetitive content, advertisements, or unsolicited promotions. Self-promotion should be relevant and non-intrusive.\n\n' +
            '5. **Mind Your Language:** Use appropriate language and tone in all communications. Profanity, offensive language, or NSFW content is not permitted.\n\n' +
            '6. **Respect Privacy:** Do not share personal information of yourself or others without consent. Respect the privacy of fellow members.\n\n' +
            '7. **Obey Discord Terms of Service:** Follow Discord\'s Terms of Service and Community Guidelines at all times.\n\n' +
            '8. **Listen to Moderators:** Follow the instructions of moderators and admins. They are here to ensure a safe and enjoyable experience for everyone.\n\n' +
            '9. **No Illegal Activities:** Do not engage in or promote any illegal activities. This includes piracy, hacking, or any other illegal behavior.\n\n' +
            '10. **Report Issues:** If you encounter any issues or have concerns, report them to moderators or admins through direct messages. Do not publicly call out other members.\n\n' +
            'By joining PaddyPool, you agree to abide by these rules. Failure to comply may result in warnings, temporary mutes, or removal from the server. Let\'s create a welcoming and inclusive community together!'
        ),
    help: {
        regularCommands: new MessageEmbed()
            .setColor('#180770')
            .setTitle('🛠️ Regular User Commands 🛠️')
            .setTimestamp(new Date())
            .setDescription('Here are the available commands for regular users:')
            .addFields(
                { name: "\u200B", value: "```help      : Display commands```" },
                { name: "\u200B", value: "```welcome   : To welcome new users```" },
                { name: "\u200B", value: "```stats     : Show overall stats```" },
                { name: "\u200B", value: "```poolstats : Show our pool stats```" },
                { name: "\u200B", value: "```workers   : DM user list of workers```" },
                { name: "\u200B", value: "```blocks    : Get last blocks (Both Verus & VARRR)```" },
                { name: "\u200B", value: "```register  : Register your account```" },
                { name: "\u200B", value: "```restore   : How to restore a native wallet (YouTube How To)```" },
                { name: "\u200B", value: "```me        : DM user address & hashrate```" }
            ),
        adminCommands: new MessageEmbed()
            .setColor('#180770')
            .setTitle('🛠️ Admin Commands 🛠️')
            .setTimestamp(new Date())
            .setDescription('Here are the available commands for admins:')
            .addFields(
                { name: "\u200B", value: "```rules     : Show server rules```" },
                { name: "\u200B", value: "```members   : Display members (Only registered members)```" },
                { name: "\u200B", value: "```referral  : Display referral ID's```" },
                { name: "\u200B", value: "```warning   : Display warning (Usage: !warning @user [reason])```" },
                { name: "\u200B", value: "```reminder  : Display reminder message```" }
            ),
        
    }
};

module.exports = embeds;